enum ThemeKeyVariables {
  colorPrimary100,
  colorPrimary200,
  colorPrimary300,
  colorPrimary400,
  colorPrimary,
  colorPrimary600,
  colorPrimary700,
  colorPrimary800,
  colorPrimary900,
  colorPrimaryTransparent100,
  colorPrimaryTransparent200,
  colorPrimaryTransparent300,
  colorPrimaryTransparent400,
  colorPrimaryTransparent500,
  colorPrimaryTransparent600,
  colorInkDark,
  colorInk,
  colorInkMid,
  colorInkLight,
  colorInkLighter,
  colorInkLightest,
  colorInkSmoke,
  colorInkTransparent300,
  colorBlack,
  colorBlackTransparent500,
  colorWhite,
  colorPurple,
  colorPurpleLight,
  colorOrange,
  colorGreen,
  colorBlue,
  colorPlatinum,
  textBasicColor,
  textHintColor,
  colorWarning,
  colorGrey,
  colorGreyBasic,
  colorDarkPurple,
  colorSemiBlack,
  colorDarkTransparent700,
  colorLightGrey,
  colorInputBackground,
}

Object.entries(ThemeKeyVariables).forEach((k) => {
  let key = k[1];
  if (key && isNaN(key)) {
    ThemeKeyVariables[key] = key;
  }
});

type ThemeDictionary = {[key in keyof typeof ThemeKeyVariables]: string};

export const ThemeKeys: ThemeDictionary = {
  colorPrimary100: 'color-primary-100',
  colorPrimary200: 'color-primary-200',
  colorPrimary300: 'color-primary-300',
  colorPrimary400: 'color-primary-400',
  colorPrimary: 'color-primary-500',
  colorPrimary600: 'color-primary-600',
  colorPrimary700: 'color-primary-700',
  colorPrimary800: 'color-primary-800',
  colorPrimary900: 'color-primary-900',
  colorPrimaryTransparent100: 'color-primary-transparent-100',
  colorPrimaryTransparent200: 'color-primary-transparent-200',
  colorPrimaryTransparent300: 'color-primary-transparent-300',
  colorPrimaryTransparent400: 'color-primary-transparent-400',
  colorPrimaryTransparent500: 'color-primary-transparent-500',
  colorPrimaryTransparent600: 'color-primary-transparent-600',
  colorInkDark: 'color-ink-dark',
  colorInk: 'color-ink',
  colorInkMid: 'color-ink-mid',
  colorInkLight: 'color-ink-light',
  colorInkLighter: 'color-ink-lighter',
  colorInkLightest: 'color-ink-lightest',
  colorInkSmoke: 'color-ink-smoke',
  colorInkTransparent300: 'color-ink-transparent-300',
  colorBlack: 'color-black',
  colorBlackTransparent500: 'color-black-transparent-500',
  colorWhite: 'color-white',
  colorPurple: 'color-purple',
  colorPurpleLight: 'color-purple-light',
  colorOrange: 'color-orange',
  colorGreen: 'color-green',
  colorBlue: 'color-blue',
  colorPlatinum: 'color-platinum',
  textBasicColor: 'text-basic-color',
  textHintColor: 'text-hint-color',
  colorWarning: 'color-warning',
  colorGrey: 'color-ink-grey',
  colorGreyBasic: 'color-grey-basic',
  colorDarkPurple: 'color-dark-purple',
  colorSemiBlack: 'color-semi-black',
  colorDarkTransparent700: 'color-dark-transparent-700',
  colorLightGrey: 'color-light-grey',
  colorInputBackground: 'color-input-background',
};
